### PR TITLE
Initial contribution of BAR Installer

### PR DESCRIPTION
**Pull request by njbartlett**
This contribution is offered to Apache Felix on behalf of Intel Corporation who funded its development.

This is a plugin for File Install that implements an ArtifactInstaller for Bundle ARchive (BAR) files. A BAR is a format representing units of functionality implemented as a collection of OSGi bundles. It includes use of the OSGi resolver API to check consistency and permits overlapping resources from multiple installable units.

For full documentation and motivation see the [installer README](https://github.com/njbartlett/felix/blob/b26396061d67811b33e080fae667424b36d634c3/fileinstall-plugins/installer/README.md).

Note that we are still working on some testing issues but I wanted to raise this PR early while these issues are being resolved, in order to open discussion with Felix committers about the contribution and to address any large-scale changes that may be required before acceptance. Thank you!

### CODE REVIEW

**Comment by tjwatson** [comment]
At first glance of the README this seems very similar to the OSGi Subsystems specification.  Can you explain the differences?

**Comment by njbartlett** [comment]
Hi Tom. I agree that the packaging mechanism looks quite similar (which is intentional) but the runtime handling is different. The resources required by a BAR are installed directly into the OSGi Framework without any kind of isolation between BARs or from the underlying framework. As such it is substantially simpler than the Subsystems spec.

**Comment by njbartlett** [comment]
BTW I have been informed that this PR will not be accepted, since I have to follow the process at http://incubator.apache.org/ip-clearance/. However I will leave this PR open for a little while to capture any comments.

**Comment by njbartlett** [comment]
Closing this PR and moving discussion to the Felix Dev mailing list: https://www.mail-archive.com/dev@felix.apache.org/msg44353.html

**Pull request closed without merging**
