### PR TITLE
FELIX-6043 ClassNotFoundException caused by org.osgi.util.function.Function

### PR DESCRIPTION
**Pull request by pleeplop**
The manifest declares org.osgi.util.function as exported but it is not embedded.
A quick fix is to declare the dependency with maven (see patch)

### CODE REVIEW

**Review by tjwatson — APPROVED** [review]
LGTM

**Review by tjwatson — COMMENTED** [review]
Actually, I think we should update the dependencies of the stuff exported to be the latest and greatest from the R7 releases.

**Comment by pleeplop** [comment]
I'm okay to update the dependencies.

Is it necessary to export these packages? Can we just import them?

**Comment by tjwatson** [comment]
I went ahead and updated the dependencies of felix scr to include function version 1.1 and promise 1.1.1.  Can you close this PR?

**Comment by pleeplop** [comment]
ok thanks

**Pull request closed without merging**
