### PR TITLE
#FELIX-5611 - BundleRepository must deal properly R5 index file with resources with relative path from the given repository’s URL

### PR DESCRIPTION
**Pull request by cvgaviao**
If the url attribute parsed from a resource are relative path then it
will be resolved against the repository location.

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi, @cvgaviao, the patch looks good, but would it be possible to also contribute some test cases? Otherwise people might break your code without knowing.

**Comment by cvgaviao** [comment]
Hi @bosschaert, 
ok I will provide some tests soon. 
regards

**Comment by cvgaviao** [comment]
Hello again @bosschaert, 
I've added the test cases.

best regards

**Comment by bosschaert** [comment]
Hi @cvgaviao, thanks for adding tests, however I get a test failure when applying the changes in this pull request:

`  <testcase classname="org.apache.felix.bundlerepository.impl.OSGiRepositoryXMLTest" name="testIdentityCapabilityForZipWithRelativePath" time="0.005">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at org.apache.felix.bundlerepository.impl.DataModelHelperImpl.repository(DataModelHelperImpl.java:98)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl$1.run(RepositoryAdminImpl.java:114)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:110)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:98)
	at org.apache.felix.bundlerepository.impl.OSGiRepositoryXMLTest.testIdentityCapabilityForZipWithRelativePath(OSGiRepositoryXMLTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:228)
	at junit.framework.TestSuite.run(TestSuite.java:223)
	at org.junit.internal.runners.OldTestClassRunner.run(OldTestClassRunner.java:35)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
</error>
  </testcase>`

**Comment by cvgaviao** [comment]
@bosschaert, that is odd... I'm getting green pass running with both maven or eclipse junit.
which OS have you used ?

The error you have faced was caused by the test not being able to find bundlerepository/src/test/resources/spec_repository.zip file

are you sure that this file is there?

**Comment by bosschaert** [comment]
@cvgaviao, this is what I'm using:

$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Java version: 1.8.0_112, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

**Comment by cvgaviao** [comment]
well, are you seeing the bundlerepository/src/test/resources/spec_repository.zip file in the project ?

**Comment by cvgaviao** [comment]
Perhaps would be good to add some assertions at here :
public Repository addRepository(URL url) throws Exception
    {
        return addRepository(url, Integer.MAX_VALUE);
    }

**Comment by bosschaert** [comment]
@cvgaviao, apologies - in the transfer of the pull request to SVN the binary test file was missed, so that caused the failure. It's all good now. Thanks for the fix!

**Pull request closed without merging**
