### PR TITLE
Fix for bug #4938

### PR DESCRIPTION
**Pull request by acartapanis**
Fix for bug #FELIX-4938

### CODE REVIEW

**Comment by acartapanis** [comment]
I have opened a jira for this (4938), but who should close it ? me ?

**Comment by bosschaert** [comment]
Thanks for the patch! I have modified it a little bit and applied it in http://svn.apache.org/viewvc?view=revision&revision=1687743

You can close this pull request now (I am not able to do it).

**Comment by acartapanis** [comment]
Great, my first patch to felix :)

**Comment by bosschaert** [comment]
Congratulations! :)

**Pull request closed without merging**
