### PR TITLE
Fixed ClassCastException caused by local resources

### PR DESCRIPTION
**Pull request by skahmann**
- Separated commits for exception fix and code cleanup

### CODE REVIEW

**Comment by bosschaert** [comment]
@skahmann thanks - your changes look good to me. I ran them through the OSGi Repository CT and those tests are still passing.

Since your change addresses an exception happening in a specific situation, would you be able to provide a unit test for it? This to ensure that this doesn't get broken again?

**Comment by bosschaert** [comment]
Associated Felix issue: https://issues.apache.org/jira/browse/FELIX-5112

**Comment by skahmann** [comment]
@bosschaert I added a test to make sure the exception was not thrown. It could be more extensive, but I'm not very familiar with mocking out all the bundle installs and resolution. Let me know if that's okay.

**Comment by bosschaert** [comment]
@skahmann thanks for the test, however if I run that test on an unmodified codebase it also passes: I simply took your test commit an applied it to the bundlerepository codebase on trunk and am seeing that it passes, so I guess it's missing something? 

I assume the test should fail if I apply it to the codebase before your code patch...

**Comment by skahmann** [comment]
@bosschaert I was not able to configure the test to run on the previous code because I rely on mocking the LocalResource interface. I did however update my test so that it runs through the deployment code. Perhaps someone more familiar with the implementations can come up with a way to test both versions.

**Comment by bosschaert** [comment]
@skahmann thanks - I'll take a look soon.

**Pull request closed without merging**
